### ISSUE TITLE
Error with name of variable when contain the character "-"

### ISSUE THREAD

**Issue by emirdeliz** [tago-io/tago-sdk-js#10]
Error with name of variable when contain the character "-". After send data in form widget the result is http 200. But in map the data is empty

![captura de tela 2017-02-16 as 17 47 29](https://cloud.githubusercontent.com/assets/6270495/23038190/4cbf4b74-f470-11e6-9e34-c7d711405286.png)

**Comment by felipefdl** [comment]
It is when use a widget post data way. (that error is on Core V1, check if on Core V2 it was already fixed)
